global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using RedNb.Nacos;
global using RedNb.Nacos.Common.Constants;
global using RedNb.Nacos.Common.Options;
global using RedNb.Nacos.Config;
